services:
  postgres:
    image: postgres:16-alpine
    container_name: music_player_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - music_player

  adminer:
    image: adminer:4
    container_name: music_player_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres:5432
      ADMINER_DESIGN: dracula
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - music_player

volumes:
  postgres_data:

networks:
  music_player:
    driver: bridge
